name: Build
on:
  pull_request:
    paths-ignore:
    - '**/README.md'
    - '**/.gitignore'
env:
  DOTNET_VERSION: 7.0.*
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  
jobs:
  build:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          include-prerelease: true
      - name: Store Secrets
        run: |
          dotnet user-secrets set "Notion" "${{ secrets.NOTION }}" --project ./tests/Notion.Sharp.Tests/Notion.Sharp.Tests.csproj 
      - name: Nuke
        run: dotnet run --project build --configuration Release
