name: Build
on:
  pull_request:
    paths-ignore:
    - '**/README.md'
env:
  DOTNET_VERSION: 7.0.*
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  
jobs:
  build:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          include-prerelease: true
      - name: Store Secrets
        run: |
          dotnet user-secrets set "Notion" "${{ secrets.NOTION }}" --project ./tests/Notion.Sharp.Tests/Notion.Sharp.Tests.csproj 
          dotnet user-secrets set "userId" "${{ secrets.USER_ID }}" --project ./tests/Notion.Sharp.Tests/Notion.Sharp.Tests.csproj 
          dotnet user-secrets set "databaseId" "${{ secrets.DATABASE_ID }}" --project ./tests/Notion.Sharp.Tests/Notion.Sharp.Tests.csproj 
          dotnet user-secrets set "pageId" "${{ secrets.PAGE_ID }}" --project ./tests/Notion.Sharp.Tests/Notion.Sharp.Tests.csproj 
          dotnet user-secrets set "blockId" "${{ secrets.BLOCK_ID }}" --project ./tests/Notion.Sharp.Tests/Notion.Sharp.Tests.csproj 
          dotnet user-secrets set "pageFromDatabase" "${{ secrets.DATABASE_PAGE }}" --project ./tests/Notion.Sharp.Tests/Notion.Sharp.Tests.csproj 
          dotnet user-secrets set "simpleDatabase" "${{ secrets.SIMPLE_DATABASE }}" --project ./tests/Notion.Sharp.Tests/Notion.Sharp.Tests.csproj 
          dotnet user-secrets set "ParentPage" "${{ secrets.PARENT_PAGE }}" --project ./tests/Notion.Sharp.Tests/Notion.Sharp.Tests.csproj 
          dotnet user-secrets set "DeletedPage" "${{ secrets.DELETED_PAGE }}" --project ./tests/Notion.Sharp.Tests/Notion.Sharp.Tests.csproj 
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build -c Release --no-restore
      - name: Test
        run: dotnet test -c Release --no-build

