name: Build
on:
  push:
    paths-ignore:
    - '**/README.md'
  pull_request:
    paths-ignore:
    - '**/README.md'
env:
  DOTNET_VERSION: 5.0.*
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  
jobs:
  build:
    runs-on: ${{ matrix.os }}
    environment: tests
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Store Secrets
        env:
          USER_ID: ${{ env.USER_ID }}
        run: |
          dotnet user-secrets set "Notion" "${{ secrets.NOTION }}" --project ./tests/Notion.Sdk.Tests/Notion.Sdk.Tests.csproj 
          dotnet user-secrets set "userId" "$USER_ID" --project ./tests/Notion.Sdk.Tests/Notion.Sdk.Tests.csproj 
          dotnet user-secrets set "databaseId" "${{ secrets.DATABASE_ID }}" --project ./tests/Notion.Sdk.Tests/Notion.Sdk.Tests.csproj 
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build -c Release --no-restore
      - name: Test
        run: dotnet test -c Release --no-build

